#ifndef MY_ERROR_H
#define MY_ERROR_H

typedef enum
{
    CONTINUE_FLAG = -1,
    SUCCESS,
    INVALID_ARGUMENT_COUNT,
    INVALID_FLAG,
    INVALID_ARGUMENT,
    MISSING_ARGUMENT,
    MEMORY_ALLOCATION_FAIL,
    NULL_POINTER_FAIL,
    CREAT_FAIL,
    OPEN_FAIL,
    READ_FAIL,
    WRITE_FAIL,
    PIPE_FAIL,
    FORK_FAIL,
    DUP2_FAIL,
    EXECLP_FAIL,
    EXECV_FAIL,
    WAITPID_FAIL,
    STRING_DUPLICATE_FAIL,
} ERROR;

#endif